Vagrant.configure("2") do |config|
if Vagrant.has_plugin? "vagrant-vbguest"
config.vbguest.no_install = true
config.vbguest.auto_update = false
config.vbguest.no_remote = true
end
config.vm.define :firewall do | firewall |
firewall.vm.box = "centos/stream8"
firewall.vm.network :private_network, ip: "192.168.50.1"
firewall.vm.network :public_network, ip: "192.168.1.100"
firewall.vm.network :forwarded_port, guest: 80, host: 9000
firewall.vm.hostname = "firewall"
firewall.vm.provision "shell", path: "firewall.sh"
end
config.vm.define :streamaSTRM do | streamaSTRM |
streamaSTRM.vm.box = "bento/centos-7"
streamaSTRM.vm.network :private_network, ip: "192.168.50.101"
streamaSTRM.vm.hostname = "streamaSTRM"
streamaSTRM.vm.provision "shell", path: "streama.sh"
end
end